kafka:
  connection:
    brokers:
      - "localhost:9092"
    username: ""
    password: ""
  consumer:
    min_bytes: 1
    max_bytes: 10e6
    topic: location

http:
  driver_port : 8081
  tracker_port: 8080
  
debug: true
